### ISSUE TITLE
on windows (0.10) chromiumlib.sizeof bombs out

### ISSUE THREAD

**Issue by jcompagner** [maketechnology/chromium.swt#79]
java.lang.UnsatisfiedLinkError: org.eclipse.swt.internal.chromium.ChromiumLib.cef_app_t_sizeof()I
	at org.eclipse.swt.internal.chromium.ChromiumLib.cef_app_t_sizeof(Native Method)
	at org.eclipse.swt.internal.chromium.cef_app_t.<clinit>(cef_app_t.java:61)
	at org.eclipse.swt.internal.chromium.CEFFactory.newApp(CEFFactory.java:34)
	at org.eclipse.swt.chromium.Chromium.initCEF(Chromium.java:258)
	at org.eclipse.swt.chromium.Chromium.create(Chromium.java:218)
	at org.eclipse.swt.chromium.Browser.<init>(Browser.java:35)

this is running from source (0.10) and fixing #77 (but that doesn't really matter if running from source)
All the native libs seems to be loaded just fine. So is that sizeof just not there?

**Comment by jcompagner** [comment]
i tried different size of calls to see if one was failing and the other not (like cef_browser_process_handler_t_sizeof() ) 
but also that fails, i tried to make it a bit more lazy (like removing the static variable there and replace it with the same call in the places where it is used) but that also doesn't work

**Comment by gzunino** [comment]
I have published new version of the p2 repo with the fix. I don't see any issue loading libraries now.

**Comment by gzunino** [comment]
I also uploaded a binary sample app for testing: 
https://github.com/maketechnology/chromium.swt/releases/tag/example.win
If you still have problems please try deleting ~/.swt folder

**Comment by jcompagner** [comment]
this is then very weird
the sample application works yes
but my eclipse (running from eclipse in debug mode) still doesn't 

![image](https://user-images.githubusercontent.com/3274268/62112475-12741b80-b2b3-11e9-86f1-b8b2e2e951db.png)

I am just using the 2 target platforms

i do suddenly get a very large libcef.so file in my swt folder (475MB)
But also after that when i run my eclipse again i get the exact same problem

**Comment by jcompagner** [comment]
I deleted the big libcef.so from the jar  (com.make.chromium.cef.win32.win32.x86_64_0.4.0.201907300353.jar) and adjusted the properties file and then the sample also works just fine

**Comment by MichaelFroeschen** [comment]
I also can't get it to run in an eclipse rcp based application.
In a standalone application it runs just fine. (As demonstrated by your example)
The sample app uses different versions of the jars, but it also runs using the jars taken from the repositories.
So it seems to be connected to being in an rcp based environment.

**Comment by gzunino** [comment]
Ok, thanks for the input. I'll try in an rcp app to check if I can reproduce.

**Comment by cladwen** [comment]
Hi, I've also experienced the same issue reported by @jcompagner. Launching an RCP application fails but the sample app works fine.

Maybe it helps: From the sample app I've found _lib/com.make.chromium.cef.win32.win32.x86_64_0.4.0.201907300353_ jar library but this version is not avalaible in p2 repository (http://dl.maketechnology.io/chromium-cef/rls/repository):
`201904250337.com.make.chromium.cef=1.0.0.077-cJlO767735K3A7C399G
a.jre.javase=10.0.0
a.jre.javase=11.0.0
com.make.chromium.cef.cocoa.macosx.x86_64=0.4.0.201904250337
com.make.chromium.cef.feature.feature.group=0.4.0.201904250337
com.make.chromium.cef.feature.feature.jar=0.4.0.201904250337
com.make.chromium.cef.gtk.linux.x86_64=0.4.0.201904250337
com.make.chromium.cef.win32.win32.x86_64=0.4.0.201904250337
config.a.jre.javase=10.0.0
config.a.jre.javase=11.0.0
Operation completed in 43086 ms.`

Kinds regards.

**Comment by jcompagner** [comment]
yes this works, so it is really some matter of a different classloader? because in the end Library.loadLibrary() does in the end System.load() with the same argument..

  public static void load(String filename) {
        Runtime.getRuntime().load0(Reflection.getCallerClass(), filename);
    }
so i guess it is that getCallerClass() that really results in that, that the lib is loaded by a different classloader?

**Comment by gzunino** [comment]
Hi @jcompagner, correct, the classloader keeps an instance of nativeLibraries loaded. In a java there is a single classLoader, but in osgi, each bundle has it's own, thus the problem. Calling Library.load makes our library be loaded by swt bundle classloaer and not chromium bundle.
