### ISSUE TITLE
DLL load issue in the latest version

### ISSUE THREAD

**Issue by V-Dev144** [maketechnology/chromium.swt#80]
As mentioned, changed the Platform.PLATFORM to SWT.getPlatform() to load swt-chromium-0100-win32.dll. After that i get the below exception,

\chromium-3071\chromium_swt_0100.dll: %1 is not a valid Win32 application

What is the issue here?

This is not happening in 0.9.1 chromium version.

_Originally posted by @vel144 in https://github.com/maketechnology/chromium.swt/issues/77#issuecomment-515382823_

**Comment by V-Dev144** [comment]
In dependency walker, it throws the below error :

"At least one file was not a 32-bit or 64-bit Windows module"

**Comment by V-Dev144** [comment]
In dependency walker, it shows the below error:

"Error: At least one file was not a 32-bit or 64-bit Windows module."

**Comment by jcompagner** [comment]
i don't seem to have that problem 
are you sure that file is not somehow corrupt?
1,10 MB (1.154.560 bytes)

thats my exact size in the user.home\.swt\xxxx\yyy\zzz dir

**Comment by V-Dev144** [comment]
@jcompagner  Yes you are right. It seems the package downloaded from github is corrupted. Then  downloaded the package from eclipse. Now dll load problem has been resolved and got the same exception as you.
java.lang.UnsatisfiedLinkError: org.eclipse.swt.internal.chromium.ChromiumLib.cef_app_t_sizeof()I

**Comment by V-Dev144** [comment]
#79

**Comment by jcompagner** [comment]
i think you need to have GIT LFS enabled for checking those large binaries out..
Could be that that corrupted it somehow

**Comment by V-Dev144** [comment]
ok thanks for the info.

**Comment by gzunino** [comment]
I have published new version of the p2 repo with the fix. I don't see any issue loading libraries now.

**Comment by gzunino** [comment]
I also uploaded a binary sample app for testing: 
https://github.com/maketechnology/chromium.swt/releases/tag/example.win
If you still have problems please try deleting ~/.swt folder

**Comment by jcompagner** [comment]
@V-Dev144 does the new build work for you? See #79 for me the sample works but in eclipse itself it still fails the same.
